### ISSUE TITLE
API versions below 1.21 are no longer supported by this library

### ISSUE THREAD

**Issue by alexall2015** [Perevalov/covid19_bot_public#1]
Hello, help please container don't start, after command sudo docker-compose up mistake
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 200, in __init__
docker.errors.InvalidVersion: API versions below 1.21 are no longer supported by this library.
[17250] Failed to execute script docker-compose

**Comment by Perevalov** [comment]
I think you have to upgrade your docker. Here is the way how to do it on Ubuntu: https://askubuntu.com/questions/1026306/how-to-upgrade-docker-server-version
